version: "3.3"
services:
  postgres-service:
    build: .
    image: postgres-it
    container_name: postgres-it
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_DB=itdb
    ports:
      - "5432:5432"
