version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
networks:
  node-network:
    driver: bridge
volumes:
  verdaccio_storage: