version: "3.3"
services:
  database:
    image: mysql:5.7.18
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rueggerllc
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=dakota
    ports:
      - "3306:3306"