version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dakota123%
      - MSSQL_PID=Developer
      - DBNAME=rueggerllc