version: "3.3"
services:
  sql.data:
    image: microsoft/mssql-server-linux
    container_name: sqlserver
    volumes:
      - /var/opt/mssql
      - ./sql:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'chmod +x ./entrypoint.sh; sh ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      - MSSQL_SA_PASSWORD=Dakota123%
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"