version: '3.1'
services:
  jenkins:
    build: .
    image: jenkins-cicd
    container_name: jenkins
    ports:
      - 8085:8080
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - cicd
volumes:
  jenkins_home:

networks:
  cicd:
    driver: bridge
