version: '3.1'
services:
  jenkins20:
    build: .
    image: jenkins-cicd
    container_name: jenkins
    ports:
      - 8081:8080
      - 5000:5000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - C:/git-repos:/home/repos
      - ./workspaces:/home/workspaces
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
volumes:
  jenkins_home: