version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - "2181:2181"
 
  kafka:
    image: wurstmeister/kafka
    container_name: kafka1
    
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: hostname
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://HP1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "readings:1:1"
