version: "3.3"
services:
  artifactory-service:
    image: docker.bintray.io/jfrog/artifactory-oss
    networks:
      - ci_net
    ports:
      - "8081:8081"
    volumes:
      - "artifactory:/var/opt/jfrog/artifactory"
      
volumes:
  artifactory:
networks:
  ci_net:
